// Copyright 2026 Jeremy and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type api_key_APIKeyConfigResponse struct {
	Prefix string `json:"prefix"`
}

type api_key_APIKeyResponse struct {
	CreatedAt     string `json:"created_at"`
	DisplayKey    string `json:"display_key"`
	ExpiresAt     string `json:"expires_at"`
	Id            string `json:"id"`
	LastUsed      string `json:"last_used"`
	MaxUsageCount int    `json:"max_usage_count"`
	Name          string `json:"name"`
	UpdatedAt     string `json:"updated_at"`
	UsageCount    int    `json:"usage_count"`
}

type api_key_APIKeyWithTokenResponse struct {
	CreatedAt     string `json:"created_at"`
	DisplayKey    string `json:"display_key"`
	ExpiresAt     string `json:"expires_at"`
	Id            string `json:"id"`
	LastUsed      string `json:"last_used"`
	MaxUsageCount int    `json:"max_usage_count"`
	Name          string `json:"name"`
	Token         string `json:"token"`
	UpdatedAt     string `json:"updated_at"`
	UsageCount    int    `json:"usage_count"`
}

type api_key_CreateAPIKeyDto struct {
	ExpiresAt     string `json:"expires_at"`
	MaxUsageCount int    `json:"max_usage_count"`
	Name          string `json:"name"`
}

type api_key_UpdateAPIKeyDto struct {
	ExpiresAt     string `json:"expires_at"`
	MaxUsageCount int    `json:"max_usage_count"`
	Name          string `json:"name"`
}

type auth_LoginDto struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Token    string `json:"token"`
}

type auth_LoginResponse struct {
	AccessToken  string          `json:"accessToken"`
	RefreshToken string          `json:"refreshToken"`
	User         json.RawMessage `json:"user"`
}

type auth_Model struct {
	Active      bool   `json:"active"`
	CreatedAt   string `json:"createdAt"`
	Email       string `json:"email"`
	Id          string `json:"id"`
	TwofaStatus bool   `json:"twofa_status"`
	UpdatedAt   string `json:"updatedAt"`
}

type auth_RefreshTokenDto struct {
	RefreshToken string `json:"refreshToken"`
}

type auth_RegisterDto struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type auth_TwoFADisableRequestDto struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type auth_TwoFASetupRequestDto struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type auth_TwoFASetupResponseDto struct {
	ProvisioningUri string `json:"provisioningUri"`
	Secret          string `json:"secret"`
}

type auth_TwoFAVerifyRequestDto struct {
	Code  string `json:"code"`
	Email string `json:"email"`
}

type auth_TwoFAVerifyResponseDto struct {
	Message string `json:"message"`
	Success bool   `json:"success"`
}

type auth_UpdatePasswordDto struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

type heartbeat_Model struct {
	DownCount int    `json:"down_count"`
	Duration  int    `json:"duration"`
	EndTime   string `json:"end_time"`
	Id        string `json:"id"`
	Important bool   `json:"important"`
	MonitorId string `json:"monitor_id"`
	Msg       string `json:"msg"`
	Notified  bool   `json:"notified"`
	Ping      int    `json:"ping"`
	Retries   int    `json:"retries"`
	Status    int    `json:"status"`
	Time      string `json:"time"`
}

type maintenance_CreateUpdateDto struct {
	Active        bool            `json:"active"`
	Cron          string          `json:"cron"`
	DaysOfMonth   json.RawMessage `json:"days_of_month"`
	Description   string          `json:"description"`
	Duration      int             `json:"duration"`
	EndDateTime   string          `json:"end_date_time"`
	EndTime       string          `json:"end_time"`
	IntervalDay   int             `json:"interval_day"`
	MonitorIds    json.RawMessage `json:"monitor_ids"`
	StartDateTime string          `json:"start_date_time"`
	StartTime     string          `json:"start_time"`
	Strategy      string          `json:"strategy"`
	Timezone      string          `json:"timezone"`
	Title         string          `json:"title"`
	Weekdays      json.RawMessage `json:"weekdays"`
}

type maintenance_MaintenanceResponseDto struct {
	Active        bool            `json:"active"`
	CreatedAt     string          `json:"created_at"`
	Cron          string          `json:"cron"`
	DaysOfMonth   json.RawMessage `json:"days_of_month"`
	Description   string          `json:"description"`
	Duration      int             `json:"duration"`
	EndDateTime   string          `json:"end_date_time"`
	EndTime       string          `json:"end_time"`
	Id            string          `json:"id"`
	IntervalDay   int             `json:"interval_day"`
	MonitorIds    json.RawMessage `json:"monitor_ids"`
	StartDateTime string          `json:"start_date_time"`
	StartTime     string          `json:"start_time"`
	Strategy      string          `json:"strategy"`
	Timezone      string          `json:"timezone"`
	Title         string          `json:"title"`
	UpdatedAt     string          `json:"updated_at"`
	Weekdays      json.RawMessage `json:"weekdays"`
}

type maintenance_Model struct {
	Active        bool            `json:"active"`
	CreatedAt     string          `json:"created_at"`
	Cron          string          `json:"cron"`
	DaysOfMonth   json.RawMessage `json:"days_of_month"`
	Description   string          `json:"description"`
	Duration      int             `json:"duration"`
	EndDateTime   string          `json:"end_date_time"`
	EndTime       string          `json:"end_time"`
	Id            string          `json:"id"`
	IntervalDay   int             `json:"interval_day"`
	StartDateTime string          `json:"start_date_time"`
	StartTime     string          `json:"start_time"`
	Strategy      string          `json:"strategy"`
	Timezone      string          `json:"timezone"`
	Title         string          `json:"title"`
	UpdatedAt     string          `json:"updated_at"`
	Weekdays      json.RawMessage `json:"weekdays"`
}

type maintenance_PartialUpdateDto struct {
	Active        bool            `json:"active"`
	Cron          string          `json:"cron"`
	DaysOfMonth   json.RawMessage `json:"days_of_month"`
	Description   string          `json:"description"`
	Duration      int             `json:"duration"`
	EndDateTime   string          `json:"end_date_time"`
	EndTime       string          `json:"end_time"`
	IntervalDay   int             `json:"interval_day"`
	MonitorIds    json.RawMessage `json:"monitor_ids"`
	StartDateTime string          `json:"start_date_time"`
	StartTime     string          `json:"start_time"`
	Strategy      string          `json:"strategy"`
	Timezone      string          `json:"timezone"`
	Title         string          `json:"title"`
	Weekdays      json.RawMessage `json:"weekdays"`
}

type monitor_CreateUpdateDto struct {
	Active          bool            `json:"active"`
	Config          string          `json:"config"`
	Interval        int             `json:"interval"`
	MaxRetries      int             `json:"max_retries"`
	Name            string          `json:"name"`
	NotificationIds json.RawMessage `json:"notification_ids"`
	ProxyId         string          `json:"proxy_id"`
	PushToken       string          `json:"push_token"`
	ResendInterval  int             `json:"resend_interval"`
	RetryInterval   int             `json:"retry_interval"`
	TagIds          json.RawMessage `json:"tag_ids"`
	Timeout         int             `json:"timeout"`
	Type            string          `json:"type"`
}

type monitor_CustomUptimeStatsDto struct {
	V24h  float64 `json:"24h"`
	V30d  float64 `json:"30d"`
	V365d float64 `json:"365d"`
	V7d   float64 `json:"7d"`
}

type monitor_Model struct {
	Active         bool   `json:"active"`
	Config         string `json:"config"`
	CreatedAt      string `json:"created_at"`
	Id             string `json:"id"`
	Interval       int    `json:"interval"`
	LastHeartbeat  string `json:"last_heartbeat"`
	MaxRetries     int    `json:"max_retries"`
	Name           string `json:"name"`
	ProxyId        string `json:"proxy_id"`
	PushToken      string `json:"push_token"`
	ResendInterval int    `json:"resend_interval"`
	RetryInterval  int    `json:"retry_interval"`
	Status         int    `json:"status"`
	Timeout        int    `json:"timeout"`
	Type           string `json:"type"`
	UpdatedAt      string `json:"updated_at"`
}

type monitor_MonitorResponseDto struct {
	Active          bool            `json:"active"`
	Config          string          `json:"config"`
	CreatedAt       string          `json:"created_at"`
	Id              string          `json:"id"`
	Interval        int             `json:"interval"`
	MaxRetries      int             `json:"max_retries"`
	Name            string          `json:"name"`
	NotificationIds json.RawMessage `json:"notification_ids"`
	ProxyId         string          `json:"proxy_id"`
	PushToken       string          `json:"push_token"`
	ResendInterval  int             `json:"resend_interval"`
	RetryInterval   int             `json:"retry_interval"`
	Status          int             `json:"status"`
	TagIds          json.RawMessage `json:"tag_ids"`
	Timeout         int             `json:"timeout"`
	Type            string          `json:"type"`
	UpdatedAt       string          `json:"updated_at"`
}

type monitor_PartialUpdateDto struct {
	Active          bool            `json:"active"`
	Config          string          `json:"config"`
	Interval        int             `json:"interval"`
	MaxRetries      int             `json:"max_retries"`
	Name            string          `json:"name"`
	NotificationIds json.RawMessage `json:"notification_ids"`
	ProxyId         string          `json:"proxy_id"`
	PushToken       string          `json:"push_token"`
	ResendInterval  int             `json:"resend_interval"`
	RetryInterval   int             `json:"retry_interval"`
	Status          string          `json:"status"`
	TagIds          json.RawMessage `json:"tag_ids"`
	Timeout         int             `json:"timeout"`
	Type            string          `json:"type"`
}

type monitor_StatPoint struct {
	Down        int     `json:"down"`
	Maintenance int     `json:"maintenance"`
	Ping        float64 `json:"ping"`
	PingMax     float64 `json:"ping_max"`
	PingMin     float64 `json:"ping_min"`
	Timestamp   int     `json:"timestamp"`
	Up          int     `json:"up"`
}

type monitor_StatPointsSummaryDto struct {
	AvgPing float64         `json:"avgPing"`
	MaxPing float64         `json:"maxPing"`
	MinPing float64         `json:"minPing"`
	Points  json.RawMessage `json:"points"`
	Uptime  float64         `json:"uptime"`
}

type notification_channel_CreateUpdateDto struct {
	Active    bool   `json:"active"`
	Config    string `json:"config"`
	IsDefault bool   `json:"is_default"`
	Name      string `json:"name"`
	Type      string `json:"type"`
}

type notification_channel_Model struct {
	Active    bool   `json:"active"`
	Config    string `json:"config"`
	CreatedAt string `json:"created_at"`
	Id        string `json:"id"`
	IsDefault bool   `json:"is_default"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	UpdatedAt string `json:"updated_at"`
}

type notification_channel_PartialUpdateDto struct {
	Active    bool   `json:"active"`
	Config    string `json:"config"`
	IsDefault bool   `json:"is_default"`
	Name      string `json:"name"`
	Type      string `json:"type"`
}

type proxy_CreateUpdateDto struct {
	Auth     bool   `json:"auth"`
	Host     string `json:"host"`
	Password string `json:"password"`
	Port     int    `json:"port"`
	Protocol string `json:"protocol"`
	Username string `json:"username"`
}

type proxy_Model struct {
	Auth        bool   `json:"auth"`
	CreatedDate string `json:"createdDate"`
	Host        string `json:"host"`
	Id          string `json:"id"`
	Password    string `json:"password"`
	Port        int    `json:"port"`
	Protocol    string `json:"protocol"`
	UpdatedAt   string `json:"updatedAt"`
	Username    string `json:"username"`
}

type proxy_PartialUpdateDto struct {
	Auth     bool   `json:"auth"`
	Host     string `json:"host"`
	Password string `json:"password"`
	Port     int    `json:"port"`
	Protocol string `json:"protocol"`
	Username string `json:"username"`
}

type setting_CreateUpdateDto struct {
	Type  string `json:"type"`
	Value string `json:"value"`
}

type setting_Model struct {
	CreatedAt string `json:"created_at"`
	Id        string `json:"id"`
	Key       string `json:"key"`
	Type      string `json:"type"`
	UpdatedAt string `json:"updated_at"`
	Value     string `json:"value"`
}

type shared_HeartBeatModel struct {
	DownCount int    `json:"down_count"`
	Duration  int    `json:"duration"`
	EndTime   string `json:"end_time"`
	Id        string `json:"id"`
	Important bool   `json:"important"`
	MonitorId string `json:"monitor_id"`
	Msg       string `json:"msg"`
	Notified  bool   `json:"notified"`
	Ping      int    `json:"ping"`
	Retries   int    `json:"retries"`
	Status    int    `json:"status"`
	Time      string `json:"time"`
}

type status_page_CreateStatusPageDTO struct {
	AutoRefreshInterval   int             `json:"auto_refresh_interval"`
	CustomCss             string          `json:"custom_css"`
	Description           string          `json:"description"`
	Domains               json.RawMessage `json:"domains"`
	FooterText            string          `json:"footer_text"`
	GoogleAnalyticsTagId  string          `json:"google_analytics_tag_id"`
	Icon                  string          `json:"icon"`
	MonitorIds            json.RawMessage `json:"monitor_ids"`
	Password              string          `json:"password"`
	Published             bool            `json:"published"`
	SearchEngineIndex     bool            `json:"search_engine_index"`
	ShowCertificateExpiry bool            `json:"show_certificate_expiry"`
	ShowPoweredBy         bool            `json:"show_powered_by"`
	ShowTags              bool            `json:"show_tags"`
	Slug                  string          `json:"slug"`
	Theme                 string          `json:"theme"`
	Title                 string          `json:"title"`
}

type status_page_Model struct {
	AutoRefreshInterval int    `json:"auto_refresh_interval"`
	CreatedAt           string `json:"created_at"`
	Description         string `json:"description"`
	FooterText          string `json:"footer_text"`
	Icon                string `json:"icon"`
	Id                  string `json:"id"`
	Published           bool   `json:"published"`
	Slug                string `json:"slug"`
	Theme               string `json:"theme"`
	Title               string `json:"title"`
	UpdatedAt           string `json:"updated_at"`
}

type status_page_MonitorWithHeartbeatsAndUptimeDTO struct {
	Active     bool            `json:"active"`
	Heartbeats json.RawMessage `json:"heartbeats"`
	Id         string          `json:"id"`
	Name       string          `json:"name"`
	Type       string          `json:"type"`
	Uptime24h  float64         `json:"uptime_24h"`
}

type status_page_PublicHeartbeatDTO struct {
	EndTime string `json:"end_time"`
	Id      string `json:"id"`
	Ping    int    `json:"ping"`
	Status  int    `json:"status"`
	Time    string `json:"time"`
}

type status_page_StatusPageWithMonitorsResponseDTO struct {
	AutoRefreshInterval   int             `json:"auto_refresh_interval"`
	CreatedAt             string          `json:"created_at"`
	CustomCss             string          `json:"custom_css"`
	Description           string          `json:"description"`
	Domains               json.RawMessage `json:"domains"`
	FooterText            string          `json:"footer_text"`
	GoogleAnalyticsTagId  string          `json:"google_analytics_tag_id"`
	Icon                  string          `json:"icon"`
	Id                    string          `json:"id"`
	MonitorIds            json.RawMessage `json:"monitor_ids"`
	Password              string          `json:"password"`
	Published             bool            `json:"published"`
	SearchEngineIndex     bool            `json:"search_engine_index"`
	ShowCertificateExpiry bool            `json:"show_certificate_expiry"`
	ShowPoweredBy         bool            `json:"show_powered_by"`
	ShowTags              bool            `json:"show_tags"`
	Slug                  string          `json:"slug"`
	Theme                 string          `json:"theme"`
	Title                 string          `json:"title"`
	UpdatedAt             string          `json:"updated_at"`
}

type status_page_UpdateStatusPageDTO struct {
	AutoRefreshInterval   int             `json:"auto_refresh_interval"`
	CustomCss             string          `json:"custom_css"`
	Description           string          `json:"description"`
	Domains               json.RawMessage `json:"domains"`
	FooterText            string          `json:"footer_text"`
	GoogleAnalyticsTagId  string          `json:"google_analytics_tag_id"`
	Icon                  string          `json:"icon"`
	MonitorIds            json.RawMessage `json:"monitor_ids"`
	Password              string          `json:"password"`
	Published             bool            `json:"published"`
	SearchEngineIndex     bool            `json:"search_engine_index"`
	ShowCertificateExpiry bool            `json:"show_certificate_expiry"`
	ShowPoweredBy         bool            `json:"show_powered_by"`
	ShowTags              bool            `json:"show_tags"`
	Slug                  string          `json:"slug"`
	Theme                 string          `json:"theme"`
	Title                 string          `json:"title"`
}

type tag_CreateUpdateDto struct {
	Color       string `json:"color"`
	Description string `json:"description"`
	Name        string `json:"name"`
}

type tag_Model struct {
	Color       string `json:"color"`
	CreatedAt   string `json:"created_at"`
	Description string `json:"description"`
	Id          string `json:"id"`
	Name        string `json:"name"`
	UpdatedAt   string `json:"updated_at"`
}

type tag_PartialUpdateDto struct {
	Color       string `json:"color"`
	Description string `json:"description"`
	Name        string `json:"name"`
}

type utils_APIError struct {
	Message string `json:"message"`
	Status  string `json:"status"`
}

type utils_ApiResponse_any struct {
	Data    string `json:"data"`
	Message string `json:"message"`
}

type utils_ApiResponse_api_key_APIKeyConfigResponse struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_api_key_APIKeyResponse struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_api_key_APIKeyWithTokenResponse struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_array_api_key_APIKeyResponse struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_array_heartbeat_Model struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_array_maintenance_Model struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_array_monitor_Model struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_array_notification_channel_Model struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_array_proxy_Model struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_array_status_page_Model struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_array_status_page_MonitorWithHeartbeatsAndUptimeDTO struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_array_tag_Model struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_auth_LoginResponse struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_maintenance_MaintenanceResponseDto struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_maintenance_Model struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_monitor_CustomUptimeStatsDto struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_monitor_Model struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_monitor_MonitorResponseDto struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_monitor_StatPointsSummaryDto struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_notification_channel_Model struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_proxy_Model struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_setting_Model struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_status_page_Model struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_status_page_StatusPageWithMonitorsResponseDTO struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}

type utils_ApiResponse_tag_Model struct {
	Data    json.RawMessage `json:"data"`
	Message string          `json:"message"`
}
