// Copyright 2026 Jeremy and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Package mcp — code-orchestration thin surface.
//
// Two tools cover the entire API: <api>_search to discover endpoints, and
// <api>_execute to invoke one. This collapses a large API (50+ endpoints)
// to ~1K tokens of tool definitions while preserving full coverage — the
// agent writes the composition logic in its own sandbox.
//
// Pattern source: Anthropic 2026-04-22 "Building agents that reach
// production systems with MCP" — Cloudflare's MCP server covers ~2,500
// endpoints in roughly 1K tokens via the same search+execute shape.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	neturl "net/url"
	"sort"
	"strings"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterCodeOrchestrationTools registers the two agent-facing tools that
// cover the whole API surface. Called from RegisterTools in place of the
// per-endpoint registrations when MCP.Orchestration is "code".
func RegisterCodeOrchestrationTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("peekaping_search",
			mcplib.WithDescription("Search the peekaping API for endpoints matching a natural-language query. Returns a ranked list of {endpoint_id, method, path, summary} entries. Call this first to find the endpoint to execute."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Natural-language description of what you want to do.")),
			mcplib.WithNumber("limit", mcplib.Description("Max endpoints to return (default 10).")),
		),
		handleCodeOrchSearch,
	)

	s.AddTool(
		mcplib.NewTool("peekaping_execute",
			mcplib.WithDescription("Execute one peekaping API endpoint by its endpoint_id (from peekaping_search). Params are passed as a JSON object; path placeholders and query strings are resolved automatically."),
			mcplib.WithString("endpoint_id", mcplib.Required(), mcplib.Description("Endpoint identifier returned by peekaping_search (e.g., \"users.list\").")),
			mcplib.WithObject("params", mcplib.Description("Parameters for the endpoint. Path placeholders match by name; remaining entries become query string on GET/DELETE or JSON body on POST/PUT/PATCH.")),
		),
		handleCodeOrchExecute,
	)
}

// codeOrchEndpoint captures the small slice of endpoint metadata the
// search+execute pair needs at runtime. `keywords` is a precomputed
// lowercase stream of description + path tokens used for naive ranking;
// anything more sophisticated belongs on the agent side.
type codeOrchEndpoint struct {
	ID         string
	Method     string
	Path       string
	Tier       string
	Summary    string
	Positional []string
	// TemplateParams carries public-to-wire bindings for promoted global path
	// placeholders. These resolve through Config.TemplateVars just like the
	// per-endpoint MCP tool inputs do.
	TemplateParams []codeOrchParamBinding
	// QueryParams carries public-to-wire bindings for spec-declared in:query
	// parameters. Write methods (POST/PUT/PATCH) route these to the query
	// string instead of dumping them into the JSON body. Derived from the
	// same mcpParamBindings location data the per-endpoint tools use.
	QueryParams []codeOrchParamBinding
	// HeaderOverrides carries per-endpoint request headers (e.g. an
	// Accept override for binary-only response endpoints). Without
	// threading these through, the code-orchestration execute path
	// sends the client's default Accept and binary endpoints 406.
	HeaderOverrides map[string]string
	// BodyIsArray marks endpoints whose request body schema root is a
	// bare top-level JSON array. The execute path then sends a top-level
	// array (the agent supplies it as params["body"]) instead of the
	// params object; a strict-mapping API rejects an object at the body
	// root with HTTP 422 "Invalid json".
	BodyIsArray bool
	keywords    []string
}

type codeOrchParamBinding struct {
	PublicName string
	WireName   string
}

// codeOrchEndpoints is the generator-populated registry covering every
// endpoint declared in the spec. Kept flat on purpose — the agent queries
// via <api>_search, so hierarchy shows up as dotted IDs, not nested maps.
var codeOrchEndpoints = []codeOrchEndpoint{
	{
		ID:             "api-keys.create",
		Method:         "POST",
		Path:           "/api-keys",
		Summary:        "Create a new API key",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("api-keys", "create", "Create a new API key", "/api-keys"),
	},
	{
		ID:             "api-keys.delete",
		Method:         "DELETE",
		Path:           "/api-keys/{id}",
		Summary:        "Delete an API key",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("api-keys", "delete", "Delete an API key", "/api-keys/{id}"),
	},
	{
		ID:             "api-keys.get",
		Method:         "GET",
		Path:           "/api-keys/{id}",
		Summary:        "Get a specific API key by ID",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("api-keys", "get", "Get a specific API key by ID", "/api-keys/{id}"),
	},
	{
		ID:             "api-keys.list",
		Method:         "GET",
		Path:           "/api-keys",
		Summary:        "Get all API keys",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("api-keys", "list", "Get all API keys", "/api-keys"),
	},
	{
		ID:             "api-keys.list-apikeys",
		Method:         "GET",
		Path:           "/api-keys/config",
		Summary:        "Get API key configuration including prefix",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("api-keys", "list-apikeys", "Get API key configuration including prefix", "/api-keys/config"),
	},
	{
		ID:             "api-keys.update",
		Method:         "PUT",
		Path:           "/api-keys/{id}",
		Summary:        "Update an API key",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("api-keys", "update", "Update an API key", "/api-keys/{id}"),
	},
	{
		ID:             "badge.cert-exp.get",
		Method:         "GET",
		Path:           "/badge/{monitorId}/cert-exp",
		Summary:        "Get certificate expiry badge",
		Positional:     []string{"monitorId"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "style", WireName: "style"}, {PublicName: "label", WireName: "label"}, {PublicName: "warnDays", WireName: "warnDays"}, {PublicName: "downDays", WireName: "downDays"}},
		keywords:       codeOrchKeywords("badge", "get", "Get certificate expiry badge", "/badge/{monitorId}/cert-exp"),
	},
	{
		ID:             "badge.ping.get",
		Method:         "GET",
		Path:           "/badge/{monitorId}/ping/{duration}",
		Summary:        "Get ping badge",
		Positional:     []string{"monitorId", "duration"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "style", WireName: "style"}, {PublicName: "label", WireName: "label"}, {PublicName: "suffix", WireName: "suffix"}, {PublicName: "color", WireName: "color"}},
		keywords:       codeOrchKeywords("badge", "get", "Get ping badge", "/badge/{monitorId}/ping/{duration}"),
	},
	{
		ID:             "badge.response.get",
		Method:         "GET",
		Path:           "/badge/{monitorId}/response",
		Summary:        "Get response time badge",
		Positional:     []string{"monitorId"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "style", WireName: "style"}, {PublicName: "label", WireName: "label"}, {PublicName: "suffix", WireName: "suffix"}, {PublicName: "color", WireName: "color"}},
		keywords:       codeOrchKeywords("badge", "get", "Get response time badge", "/badge/{monitorId}/response"),
	},
	{
		ID:             "badge.status.get",
		Method:         "GET",
		Path:           "/badge/{monitorId}/status",
		Summary:        "Get status badge",
		Positional:     []string{"monitorId"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "style", WireName: "style"}, {PublicName: "upLabel", WireName: "upLabel"}, {PublicName: "downLabel", WireName: "downLabel"}, {PublicName: "upColor", WireName: "upColor"}, {PublicName: "downColor", WireName: "downColor"}},
		keywords:       codeOrchKeywords("badge", "get", "Get status badge", "/badge/{monitorId}/status"),
	},
	{
		ID:             "badge.uptime.get",
		Method:         "GET",
		Path:           "/badge/{monitorId}/uptime/{duration}",
		Summary:        "Get uptime badge",
		Positional:     []string{"monitorId", "duration"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "style", WireName: "style"}, {PublicName: "label", WireName: "label"}, {PublicName: "suffix", WireName: "suffix"}, {PublicName: "color", WireName: "color"}},
		keywords:       codeOrchKeywords("badge", "get", "Get uptime badge", "/badge/{monitorId}/uptime/{duration}"),
	},
	{
		ID:             "health.list",
		Method:         "GET",
		Path:           "/health",
		Summary:        "Returns the current server health",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("health", "list", "Returns the current server health", "/health"),
	},
	{
		ID:             "maintenances.create",
		Method:         "POST",
		Path:           "/maintenances",
		Summary:        "Create maintenance",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("maintenances", "create", "Create maintenance", "/maintenances"),
	},
	{
		ID:             "maintenances.delete",
		Method:         "DELETE",
		Path:           "/maintenances/{id}",
		Summary:        "Delete maintenance",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("maintenances", "delete", "Delete maintenance", "/maintenances/{id}"),
	},
	{
		ID:             "maintenances.get",
		Method:         "GET",
		Path:           "/maintenances/{id}",
		Summary:        "Get maintenance by ID",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("maintenances", "get", "Get maintenance by ID", "/maintenances/{id}"),
	},
	{
		ID:             "maintenances.list",
		Method:         "GET",
		Path:           "/maintenances",
		Summary:        "Get maintenances",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "q", WireName: "q"}, {PublicName: "strategy", WireName: "strategy"}, {PublicName: "page", WireName: "page"}, {PublicName: "limit", WireName: "limit"}},
		keywords:       codeOrchKeywords("maintenances", "list", "Get maintenances", "/maintenances"),
	},
	{
		ID:             "maintenances.update",
		Method:         "PATCH",
		Path:           "/maintenances/{id}",
		Summary:        "Update maintenance",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("maintenances", "update", "Update maintenance", "/maintenances/{id}"),
	},
	{
		ID:             "maintenances.update-id",
		Method:         "PUT",
		Path:           "/maintenances/{id}",
		Summary:        "Update maintenance",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("maintenances", "update-id", "Update maintenance", "/maintenances/{id}"),
	},
	{
		ID:             "maintenances.pause.update",
		Method:         "PATCH",
		Path:           "/maintenances/{id}/pause",
		Summary:        "Pause maintenance",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("maintenances", "update", "Pause maintenance", "/maintenances/{id}/pause"),
	},
	{
		ID:             "maintenances.resume.update",
		Method:         "PATCH",
		Path:           "/maintenances/{id}/resume",
		Summary:        "Resume maintenance",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("maintenances", "update", "Resume maintenance", "/maintenances/{id}/resume"),
	},
	{
		ID:             "monitors.create",
		Method:         "POST",
		Path:           "/monitors",
		Summary:        "Create monitor",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("monitors", "create", "Create monitor", "/monitors"),
	},
	{
		ID:             "monitors.delete",
		Method:         "DELETE",
		Path:           "/monitors/{id}",
		Summary:        "Delete monitor",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("monitors", "delete", "Delete monitor", "/monitors/{id}"),
	},
	{
		ID:             "monitors.get",
		Method:         "GET",
		Path:           "/monitors/{id}",
		Summary:        "Get monitor by ID",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("monitors", "get", "Get monitor by ID", "/monitors/{id}"),
	},
	{
		ID:             "monitors.list",
		Method:         "GET",
		Path:           "/monitors",
		Summary:        "Get monitors",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "q", WireName: "q"}, {PublicName: "page", WireName: "page"}, {PublicName: "limit", WireName: "limit"}, {PublicName: "active", WireName: "active"}, {PublicName: "status", WireName: "status"}, {PublicName: "tag_ids", WireName: "tag_ids"}},
		keywords:       codeOrchKeywords("monitors", "list", "Get monitors", "/monitors"),
	},
	{
		ID:             "monitors.list-batch",
		Method:         "GET",
		Path:           "/monitors/batch",
		Summary:        "Get monitors by IDs",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "ids", WireName: "ids"}},
		keywords:       codeOrchKeywords("monitors", "list-batch", "Get monitors by IDs", "/monitors/batch"),
	},
	{
		ID:             "monitors.update",
		Method:         "PATCH",
		Path:           "/monitors/{id}",
		Summary:        "Update monitor",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("monitors", "update", "Update monitor", "/monitors/{id}"),
	},
	{
		ID:             "monitors.update-id",
		Method:         "PUT",
		Path:           "/monitors/{id}",
		Summary:        "Update monitor",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("monitors", "update-id", "Update monitor", "/monitors/{id}"),
	},
	{
		ID:             "monitors.heartbeats.get",
		Method:         "GET",
		Path:           "/monitors/{id}/heartbeats",
		Summary:        "Get paginated heartbeats for a monitor",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "limit", WireName: "limit"}, {PublicName: "page", WireName: "page"}, {PublicName: "important", WireName: "important"}, {PublicName: "reverse", WireName: "reverse"}},
		keywords:       codeOrchKeywords("monitors", "get", "Get paginated heartbeats for a monitor", "/monitors/{id}/heartbeats"),
	},
	{
		ID:             "monitors.reset.create",
		Method:         "POST",
		Path:           "/monitors/{id}/reset",
		Summary:        "Reset monitor data (heartbeats and stats)",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("monitors", "create", "Reset monitor data (heartbeats and stats)", "/monitors/{id}/reset"),
	},
	{
		ID:             "monitors.stats.get",
		Method:         "GET",
		Path:           "/monitors/{id}/stats/points",
		Summary:        "Get monitor stat points (ping/up/down) from stats tables",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "since", WireName: "since"}, {PublicName: "until", WireName: "until"}, {PublicName: "granularity", WireName: "granularity"}},
		keywords:       codeOrchKeywords("monitors", "get", "Get monitor stat points (ping/up/down) from stats tables", "/monitors/{id}/stats/points"),
	},
	{
		ID:             "monitors.stats.get-monitors",
		Method:         "GET",
		Path:           "/monitors/{id}/stats/uptime",
		Summary:        "Get monitor uptime stats (24h, 30d, 365d)",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("monitors", "get-monitors", "Get monitor uptime stats (24h, 30d, 365d)", "/monitors/{id}/stats/uptime"),
	},
	{
		ID:             "monitors.tls.get",
		Method:         "GET",
		Path:           "/monitors/{id}/tls",
		Summary:        "Get monitor TLS certificate information",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("monitors", "get", "Get monitor TLS certificate information", "/monitors/{id}/tls"),
	},
	{
		ID:             "notification-channels.create",
		Method:         "POST",
		Path:           "/notification-channels",
		Summary:        "Create notification channel",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("notification-channels", "create", "Create notification channel", "/notification-channels"),
	},
	{
		ID:             "notification-channels.create-notificationchannels",
		Method:         "POST",
		Path:           "/notification-channels/test",
		Summary:        "Test notification channel",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("notification-channels", "create-notificationchannels", "Test notification channel", "/notification-channels/test"),
	},
	{
		ID:             "notification-channels.delete",
		Method:         "DELETE",
		Path:           "/notification-channels/{id}",
		Summary:        "Delete notification channel",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("notification-channels", "delete", "Delete notification channel", "/notification-channels/{id}"),
	},
	{
		ID:             "notification-channels.get",
		Method:         "GET",
		Path:           "/notification-channels/{id}",
		Summary:        "Get notification channel by ID",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("notification-channels", "get", "Get notification channel by ID", "/notification-channels/{id}"),
	},
	{
		ID:             "notification-channels.list",
		Method:         "GET",
		Path:           "/notification-channels",
		Summary:        "Get notification channels",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "q", WireName: "q"}, {PublicName: "page", WireName: "page"}, {PublicName: "limit", WireName: "limit"}},
		keywords:       codeOrchKeywords("notification-channels", "list", "Get notification channels", "/notification-channels"),
	},
	{
		ID:             "notification-channels.update",
		Method:         "PATCH",
		Path:           "/notification-channels/{id}",
		Summary:        "Update notification channel",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("notification-channels", "update", "Update notification channel", "/notification-channels/{id}"),
	},
	{
		ID:             "notification-channels.update-notificationchannels",
		Method:         "PUT",
		Path:           "/notification-channels/{id}",
		Summary:        "Update notification channel",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("notification-channels", "update-notificationchannels", "Update notification channel", "/notification-channels/{id}"),
	},
	{
		ID:             "peekaping-auth.create",
		Method:         "POST",
		Path:           "/auth/login",
		Summary:        "Login admin",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("peekaping-auth", "create", "Login admin", "/auth/login"),
	},
	{
		ID:             "peekaping-auth.create-2fa",
		Method:         "POST",
		Path:           "/auth/2fa/disable",
		Summary:        "Disable 2FA (TOTP) for user",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("peekaping-auth", "create-2fa", "Disable 2FA (TOTP) for user", "/auth/2fa/disable"),
	},
	{
		ID:             "peekaping-auth.create-2fa-2",
		Method:         "POST",
		Path:           "/auth/2fa/setup",
		Summary:        "Enable 2FA (TOTP) for user",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("peekaping-auth", "create-2fa-2", "Enable 2FA (TOTP) for user", "/auth/2fa/setup"),
	},
	{
		ID:             "peekaping-auth.create-2fa-3",
		Method:         "POST",
		Path:           "/auth/2fa/verify",
		Summary:        "Verify 2FA (TOTP) code for user",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("peekaping-auth", "create-2fa-3", "Verify 2FA (TOTP) code for user", "/auth/2fa/verify"),
	},
	{
		ID:             "peekaping-auth.create-refresh",
		Method:         "POST",
		Path:           "/auth/refresh",
		Summary:        "Refresh access token",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("peekaping-auth", "create-refresh", "Refresh access token", "/auth/refresh"),
	},
	{
		ID:             "peekaping-auth.create-register",
		Method:         "POST",
		Path:           "/auth/register",
		Summary:        "Register new admin",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("peekaping-auth", "create-register", "Register new admin", "/auth/register"),
	},
	{
		ID:             "peekaping-auth.update",
		Method:         "PUT",
		Path:           "/auth/password",
		Summary:        "Update user password",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("peekaping-auth", "update", "Update user password", "/auth/password"),
	},
	{
		ID:             "peekaping-version.list",
		Method:         "GET",
		Path:           "/version",
		Summary:        "Returns the current server version",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("peekaping-version", "list", "Returns the current server version", "/version"),
	},
	{
		ID:             "proxies.create",
		Method:         "POST",
		Path:           "/proxies",
		Summary:        "Create proxy",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("proxies", "create", "Create proxy", "/proxies"),
	},
	{
		ID:             "proxies.delete",
		Method:         "DELETE",
		Path:           "/proxies/{id}",
		Summary:        "Delete proxy",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("proxies", "delete", "Delete proxy", "/proxies/{id}"),
	},
	{
		ID:             "proxies.get",
		Method:         "GET",
		Path:           "/proxies/{id}",
		Summary:        "Get proxy by ID",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("proxies", "get", "Get proxy by ID", "/proxies/{id}"),
	},
	{
		ID:             "proxies.list",
		Method:         "GET",
		Path:           "/proxies",
		Summary:        "Get proxies",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "q", WireName: "q"}, {PublicName: "page", WireName: "page"}, {PublicName: "limit", WireName: "limit"}},
		keywords:       codeOrchKeywords("proxies", "list", "Get proxies", "/proxies"),
	},
	{
		ID:             "proxies.update",
		Method:         "PATCH",
		Path:           "/proxies/{id}",
		Summary:        "Update proxy",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("proxies", "update", "Update proxy", "/proxies/{id}"),
	},
	{
		ID:             "proxies.update-id",
		Method:         "PUT",
		Path:           "/proxies/{id}",
		Summary:        "Update proxy",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("proxies", "update-id", "Update proxy", "/proxies/{id}"),
	},
	{
		ID:             "settings.delete",
		Method:         "DELETE",
		Path:           "/settings/key/{key}",
		Summary:        "Delete setting by key",
		Positional:     []string{"key"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("settings", "delete", "Delete setting by key", "/settings/key/{key}"),
	},
	{
		ID:             "settings.get",
		Method:         "GET",
		Path:           "/settings/key/{key}",
		Summary:        "Get setting by key",
		Positional:     []string{"key"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("settings", "get", "Get setting by key", "/settings/key/{key}"),
	},
	{
		ID:             "settings.update",
		Method:         "PUT",
		Path:           "/settings/key/{key}",
		Summary:        "Set setting by key",
		Positional:     []string{"key"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("settings", "update", "Set setting by key", "/settings/key/{key}"),
	},
	{
		ID:             "status-pages.create",
		Method:         "POST",
		Path:           "/status-pages",
		Summary:        "Create a new status page",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("status-pages", "create", "Create a new status page", "/status-pages"),
	},
	{
		ID:             "status-pages.delete",
		Method:         "DELETE",
		Path:           "/status-pages/{id}",
		Summary:        "Delete a status page",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("status-pages", "delete", "Delete a status page", "/status-pages/{id}"),
	},
	{
		ID:             "status-pages.get",
		Method:         "GET",
		Path:           "/status-pages/{id}",
		Summary:        "Get a status page by ID",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("status-pages", "get", "Get a status page by ID", "/status-pages/{id}"),
	},
	{
		ID:             "status-pages.get-statuspages",
		Method:         "GET",
		Path:           "/status-pages/domain/{domain}",
		Summary:        "Get a status page by domain name",
		Positional:     []string{"domain"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("status-pages", "get-statuspages", "Get a status page by domain name", "/status-pages/domain/{domain}"),
	},
	{
		ID:             "status-pages.get-statuspages-2",
		Method:         "GET",
		Path:           "/status-pages/slug/{slug}",
		Summary:        "Get a status page by slug",
		Positional:     []string{"slug"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("status-pages", "get-statuspages-2", "Get a status page by slug", "/status-pages/slug/{slug}"),
	},
	{
		ID:             "status-pages.get-statuspages-3",
		Method:         "GET",
		Path:           "/status-pages/slug/{slug}/monitors",
		Summary:        "Get monitors for a status page by slug with heartbeats and uptime",
		Positional:     []string{"slug"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("status-pages", "get-statuspages-3", "Get monitors for a status page by slug with heartbeats and uptime", "/status-pages/slug/{slug}/monitors"),
	},
	{
		ID:             "status-pages.get-statuspages-4",
		Method:         "GET",
		Path:           "/status-pages/slug/{slug}/monitors/homepage",
		Summary:        "Get monitors for a status page by slug for homepage",
		Positional:     []string{"slug"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("status-pages", "get-statuspages-4", "Get monitors for a status page by slug for homepage", "/status-pages/slug/{slug}/monitors/homepage"),
	},
	{
		ID:             "status-pages.list",
		Method:         "GET",
		Path:           "/status-pages",
		Summary:        "Get all status pages",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "q", WireName: "q"}, {PublicName: "page", WireName: "page"}, {PublicName: "limit", WireName: "limit"}},
		keywords:       codeOrchKeywords("status-pages", "list", "Get all status pages", "/status-pages"),
	},
	{
		ID:             "status-pages.update",
		Method:         "PATCH",
		Path:           "/status-pages/{id}",
		Summary:        "Update a status page",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("status-pages", "update", "Update a status page", "/status-pages/{id}"),
	},
	{
		ID:             "tags.create",
		Method:         "POST",
		Path:           "/tags",
		Summary:        "Create tag",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("tags", "create", "Create tag", "/tags"),
	},
	{
		ID:             "tags.delete",
		Method:         "DELETE",
		Path:           "/tags/{id}",
		Summary:        "Delete tag",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("tags", "delete", "Delete tag", "/tags/{id}"),
	},
	{
		ID:             "tags.get",
		Method:         "GET",
		Path:           "/tags/{id}",
		Summary:        "Get tag by ID",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("tags", "get", "Get tag by ID", "/tags/{id}"),
	},
	{
		ID:             "tags.list",
		Method:         "GET",
		Path:           "/tags",
		Summary:        "Get tags",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "q", WireName: "q"}, {PublicName: "page", WireName: "page"}, {PublicName: "limit", WireName: "limit"}},
		keywords:       codeOrchKeywords("tags", "list", "Get tags", "/tags"),
	},
	{
		ID:             "tags.update",
		Method:         "PATCH",
		Path:           "/tags/{id}",
		Summary:        "Update tag",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("tags", "update", "Update tag", "/tags/{id}"),
	},
	{
		ID:             "tags.update-id",
		Method:         "PUT",
		Path:           "/tags/{id}",
		Summary:        "Update tag",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("tags", "update-id", "Update tag", "/tags/{id}"),
	},
}

// codeOrchStopwords filters two-letter and short common-word substrings
// that pollute ranking via the substring-contains rule. Without them, a
// search for "list links" matches every endpoint whose description
// contains "is enrolled" because "is" is two chars and the matcher
// accepts kw.contains(t) || t.contains(kw).
var codeOrchStopwords = map[string]bool{
	"a": true, "an": true, "and": true, "are": true, "as": true,
	"at": true, "be": true, "by": true, "for": true, "from": true,
	"has": true, "in": true, "is": true, "it": true, "its": true,
	"of": true, "on": true, "or": true, "that": true, "the": true,
	"this": true, "to": true, "was": true, "will": true, "with": true,
	"your": true, "you": true, "any": true, "all": true,
}

// codeOrchKeywords produces the lowercase token stream used for search
// ranking. Defined at package level so the registry initializer can call it
// inline above without pulling in a separate precompute step.
func codeOrchKeywords(resource, endpoint, summary, path string) []string {
	raw := strings.ToLower(resource + " " + endpoint + " " + summary + " " + path)
	raw = strings.Map(func(r rune) rune {
		switch r {
		case '_', '-', '/', '{', '}', '.', ',', ':', ';':
			return ' '
		}
		return r
	}, raw)
	out := make([]string, 0, 16)
	seen := map[string]bool{}
	for _, tok := range strings.Fields(raw) {
		if len(tok) < 3 || codeOrchStopwords[tok] || seen[tok] {
			continue
		}
		seen[tok] = true
		out = append(out, tok)
	}
	return out
}

func handleCodeOrchSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || strings.TrimSpace(query) == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}
	limit := 10
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	terms := codeOrchKeywords("", "", query, "")
	type scored struct {
		ep    *codeOrchEndpoint
		score int
	}
	results := make([]scored, 0, len(codeOrchEndpoints))
	for i := range codeOrchEndpoints {
		ep := &codeOrchEndpoints[i]
		score := 0
		for _, t := range terms {
			for _, kw := range ep.keywords {
				if kw == t {
					score += 2
				} else if strings.Contains(kw, t) || strings.Contains(t, kw) {
					score++
				}
			}
		}
		if score > 0 {
			results = append(results, scored{ep: ep, score: score})
		}
	}
	sort.SliceStable(results, func(i, j int) bool { return results[i].score > results[j].score })
	if len(results) > limit {
		results = results[:limit]
	}

	out := make([]map[string]any, 0, len(results))
	for _, r := range results {
		out = append(out, map[string]any{
			"endpoint_id": r.ep.ID,
			"method":      r.ep.Method,
			"path":        r.ep.Path,
			"summary":     r.ep.Summary,
			"score":       r.score,
		})
	}
	data, _ := json.Marshal(map[string]any{"count": len(out), "results": out})
	return mcplib.NewToolResultText(string(data)), nil
}

func handleCodeOrchExecute(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	id, ok := args["endpoint_id"].(string)
	if !ok || id == "" {
		return mcplib.NewToolResultError("endpoint_id is required (call peekaping_search first)"), nil
	}

	var ep *codeOrchEndpoint
	for i := range codeOrchEndpoints {
		if codeOrchEndpoints[i].ID == id {
			ep = &codeOrchEndpoints[i]
			break
		}
	}
	if ep == nil {
		return mcplib.NewToolResultError(fmt.Sprintf("unknown endpoint_id %q — call peekaping_search to discover valid ids", id)), nil
	}

	params, _ := args["params"].(map[string]any)
	if params == nil {
		params = map[string]any{}
	}

	c, err := newMCPClient()
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	path := ep.Path
	for _, p := range ep.Positional {
		if v, ok := params[p]; ok {
			path = strings.ReplaceAll(path, "{"+p+"}", fmt.Sprintf("%v", v))
			delete(params, p)
		}
	}

	// Route params to their runtime slots. GET/DELETE params are query
	// strings; write methods split spec-declared query params from the
	// remaining params used as the request body below.
	query := map[string]string{}
	if ep.Method == "GET" || ep.Method == "DELETE" {
		for k, v := range params {
			query[codeOrchWireQueryName(ep.QueryParams, k)] = fmt.Sprintf("%v", v)
		}
	} else {
		// Route spec-declared in:query params to the query string for write
		// methods too. Without this, a query param (e.g. sendToLedger on
		// PUT /ledger/voucher/{id}) wrongly lands in the JSON body and the
		// API silently ignores it or rejects the request. The remaining
		// params stay in the map for codeOrchWriteBody (the JSON body).
		if enc := codeOrchSplitQuery(ep.QueryParams, params); enc != "" {
			sep := "?"
			if strings.Contains(path, "?") {
				sep = "&"
			}
			path += sep + enc
		}
	}

	hdrs := ep.HeaderOverrides
	writeBody := func() any {
		if ep.BodyIsArray {
			return codeOrchArrayBody(params)
		}
		return codeOrchWriteBody(params)
	}
	var data json.RawMessage
	switch ep.Method {
	case "GET":
		if len(hdrs) > 0 {
			data, err = c.GetWithHeaders(ctx, path, query, hdrs)
		} else {
			data, err = c.Get(ctx, path, query)
		}
	case "DELETE":
		if len(hdrs) > 0 {
			data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, query, hdrs)
		} else {
			data, _, err = c.DeleteWithParams(ctx, path, query)
		}
	case "POST":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PostWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Post(ctx, path, body)
		}
	case "PUT":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PutWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Put(ctx, path, body)
		}
	case "PATCH":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PatchWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Patch(ctx, path, body)
		}
	default:
		return mcplib.NewToolResultError(fmt.Sprintf("unsupported method %q", ep.Method)), nil
	}
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	return mcplib.NewToolResultText(string(data)), nil
}

// codeOrchWriteBody returns the value handed to the client layer as the
// request body for write methods (POST/PUT/PATCH). It MUST be the structured
// params map, never pre-marshaled bytes.
//
// client.do() marshals the body value exactly once. Handing it []byte makes
// json.Marshal([]byte) emit a base64-encoded JSON *string*, so the API
// receives "eyJ...==" where it expects the request object. Strict JSON APIs
// reject that as the wrong type at the body root. GET/DELETE carry no body,
// so this defect stays latent until the first write attempt.
func codeOrchWriteBody(params map[string]any) any {
	return params
}

// codeOrchArrayBody returns the request body for endpoints whose schema root
// is a bare top-level JSON array (ep.BodyIsArray). Such a body cannot be
// expressed as the params object, so the agent supplies the array under the
// conventional params key "body" (these endpoints have no flattened named
// params, so there is no collision risk). When present and array-shaped it is
// sent as the top-level array the API expects. Otherwise params is returned
// unchanged so a malformed call fails loudly at the API (HTTP 422) instead of
// silently sending the wrong shape or a partial write — financial mutations
// are never retried with body-variant guesses (broken-convenience guardrail).
func codeOrchArrayBody(params map[string]any) any {
	if v, ok := params["body"]; ok {
		if arr, ok := v.([]any); ok {
			return arr
		}
	}
	return params
}

// codeOrchSplitQuery removes spec-declared in:query params from params and
// returns them URL-encoded for appending to the request path. The remaining
// entries stay in the map for codeOrchWriteBody (the JSON body), so a write
// method's query parameters never get buried in the body. Mutates params by
// design (deletes the consumed query keys).
func codeOrchSplitQuery(queryParams []codeOrchParamBinding, params map[string]any) string {
	uv := neturl.Values{}
	for _, q := range queryParams {
		for _, key := range []string{q.PublicName, q.WireName} {
			if key == "" {
				continue
			}
			if v, ok := params[key]; ok {
				uv.Set(q.WireName, fmt.Sprintf("%v", v))
				delete(params, key)
				break
			}
		}
	}
	return uv.Encode()
}

func codeOrchWireQueryName(queryParams []codeOrchParamBinding, name string) string {
	for _, q := range queryParams {
		if q.PublicName == name || q.WireName == name {
			return q.WireName
		}
	}
	return name
}
