// Copyright 2026 Jeremy and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBadgeUptimeCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "uptime",
		Short:       "Get uptime for badge",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newBadgeUptimeGetCmd(flags))
	return cmd
}
