// Copyright 2026 Jeremy and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMaintenancesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "maintenances",
		Short:       "List, get, create, update, and delete maintenances",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newMaintenancesCreateCmd(flags))
	cmd.AddCommand(newMaintenancesDeleteCmd(flags))
	cmd.AddCommand(newMaintenancesGetCmd(flags))
	cmd.AddCommand(newMaintenancesListCmd(flags))
	cmd.AddCommand(newMaintenancesUpdateCmd(flags))
	cmd.AddCommand(newMaintenancesUpdateIdCmd(flags))
	cmd.AddCommand(newMaintenancesPauseCmd(flags))
	cmd.AddCommand(newMaintenancesResumeCmd(flags))
	return cmd
}
