// Copyright 2026 Jeremy and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
	"peekaping-pp-cli/internal/cliutil"
)

func newMaintenancesCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyActive bool
	var bodyCron string
	var bodyDaysOfMonth string
	var bodyDescription string
	var bodyDuration int
	var bodyEndDateTime string
	var bodyEndTime string
	var bodyIntervalDay int
	var bodyMonitorIds string
	var bodyStartDateTime string
	var bodyStartTime string
	var bodyStrategy string
	var bodyTimezone string
	var bodyTitle string
	var bodyWeekdays string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create",
		Short:       "Create maintenance",
		Example:     "  peekaping-pp-cli maintenances create --strategy example-value",
		Annotations: map[string]string{"pp:endpoint": "maintenances.create", "pp:method": "POST", "pp:path": "/maintenances"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("strategy") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "strategy")
				}
				if !cmd.Flags().Changed("title") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "title")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/maintenances"
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if cmd.Flags().Changed("active") {
					body["active"] = bodyActive
				}
				if bodyCron != "" {
					body["cron"] = bodyCron
				}
				if bodyDaysOfMonth != "" {
					var parsedDaysOfMonth any
					if err := json.Unmarshal([]byte(bodyDaysOfMonth), &parsedDaysOfMonth); err != nil {
						return fmt.Errorf("parsing --days-of-month JSON: %w", err)
					}
					body["days_of_month"] = parsedDaysOfMonth
				}
				if bodyDescription != "" {
					body["description"] = bodyDescription
				}
				if bodyDuration != 0 {
					body["duration"] = bodyDuration
				}
				if bodyEndDateTime != "" {
					body["end_date_time"] = bodyEndDateTime
				}
				if bodyEndTime != "" {
					body["end_time"] = bodyEndTime
				}
				if bodyIntervalDay != 0 {
					body["interval_day"] = bodyIntervalDay
				}
				if bodyMonitorIds != "" {
					body["monitor_ids"] = cliutil.SplitCSV(bodyMonitorIds)
				}
				if bodyStartDateTime != "" {
					body["start_date_time"] = bodyStartDateTime
				}
				if bodyStartTime != "" {
					body["start_time"] = bodyStartTime
				}
				if bodyStrategy != "" {
					body["strategy"] = bodyStrategy
				}
				if bodyTimezone != "" {
					body["timezone"] = bodyTimezone
				}
				if bodyTitle != "" {
					body["title"] = bodyTitle
				}
				if bodyWeekdays != "" {
					var parsedWeekdays any
					if err := json.Unmarshal([]byte(bodyWeekdays), &parsedWeekdays); err != nil {
						return fmt.Errorf("parsing --weekdays JSON: %w", err)
					}
					body["weekdays"] = parsedWeekdays
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "maintenances", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "maintenances", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "maintenances", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "maintenances", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "maintenances", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "maintenances",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "maintenances", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "maintenances", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().BoolVar(&bodyActive, "active", false, "Active")
	cmd.Flags().StringVar(&bodyCron, "cron", "", "Cron")
	cmd.Flags().StringVar(&bodyDaysOfMonth, "days-of-month", "", "Days of month")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "Description")
	cmd.Flags().IntVar(&bodyDuration, "duration", 0, "Duration")
	cmd.Flags().StringVar(&bodyEndDateTime, "end-date-time", "", "End date time")
	cmd.Flags().StringVar(&bodyEndTime, "end-time", "", "End time")
	cmd.Flags().IntVar(&bodyIntervalDay, "interval-day", 0, "Interval day")
	cmd.Flags().StringVar(&bodyMonitorIds, "monitor-ids", "", "Monitor ids")
	cmd.Flags().StringVar(&bodyStartDateTime, "start-date-time", "", "Start date time")
	cmd.Flags().StringVar(&bodyStartTime, "start-time", "", "Start time")
	cmd.Flags().StringVar(&bodyStrategy, "strategy", "", "Strategy")
	cmd.Flags().StringVar(&bodyTimezone, "timezone", "", "Timezone")
	cmd.Flags().StringVar(&bodyTitle, "title", "", "Title")
	cmd.Flags().StringVar(&bodyWeekdays, "weekdays", "", "Weekdays")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
