// Copyright 2026 Jeremy and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
	"peekaping-pp-cli/internal/cliutil"
)

func newMonitorsUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyActive bool
	var bodyConfig string
	var bodyInterval int
	var bodyMaxRetries int
	var bodyName string
	var bodyNotificationIds string
	var bodyProxyId string
	var bodyPushToken string
	var bodyResendInterval int
	var bodyRetryInterval int
	var bodyStatus int
	var bodyTagIds string
	var bodyTimeout int
	var bodyType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update <id>",
		Short:       "Update monitor",
		Example:     "  peekaping-pp-cli monitors update 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "monitors.update", "pp:method": "PATCH", "pp:path": "/monitors/{id}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/monitors/{id}"
			path = replacePathParam(path, "id", args[0])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if cmd.Flags().Changed("active") {
					body["active"] = bodyActive
				}
				if bodyConfig != "" {
					body["config"] = bodyConfig
				}
				if bodyInterval != 0 {
					body["interval"] = bodyInterval
				}
				if bodyMaxRetries != 0 {
					body["max_retries"] = bodyMaxRetries
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
				if bodyNotificationIds != "" {
					body["notification_ids"] = cliutil.SplitCSV(bodyNotificationIds)
				}
				if bodyProxyId != "" {
					body["proxy_id"] = bodyProxyId
				}
				if bodyPushToken != "" {
					body["push_token"] = bodyPushToken
				}
				if bodyResendInterval != 0 {
					body["resend_interval"] = bodyResendInterval
				}
				if bodyRetryInterval != 0 {
					body["retry_interval"] = bodyRetryInterval
				}
				if bodyStatus != 0 {
					body["status"] = bodyStatus
				}
				if bodyTagIds != "" {
					body["tag_ids"] = cliutil.SplitCSV(bodyTagIds)
				}
				if bodyTimeout != 0 {
					body["timeout"] = bodyTimeout
				}
				if bodyType != "" {
					body["type"] = bodyType
				}
			}
			data, statusCode, err := c.PatchWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "monitors", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "monitors", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "monitors", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "monitors", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "monitors", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "patch",
					"resource": "monitors",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "monitors", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "monitors", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().BoolVar(&bodyActive, "active", false, "Active")
	cmd.Flags().StringVar(&bodyConfig, "config", "", "Config")
	cmd.Flags().IntVar(&bodyInterval, "interval", 0, "Interval")
	cmd.Flags().IntVar(&bodyMaxRetries, "max-retries", 0, "Max retries")
	cmd.Flags().StringVar(&bodyName, "name", "", "Name")
	cmd.Flags().StringVar(&bodyNotificationIds, "notification-ids", "", "Notification ids")
	cmd.Flags().StringVar(&bodyProxyId, "proxy-id", "", "Proxy id")
	cmd.Flags().StringVar(&bodyPushToken, "push-token", "", "Push token")
	cmd.Flags().IntVar(&bodyResendInterval, "resend-interval", 0, "Resend interval")
	cmd.Flags().IntVar(&bodyRetryInterval, "retry-interval", 0, "Retry interval")
	cmd.Flags().IntVar(&bodyStatus, "status", 0, "Status")
	cmd.Flags().StringVar(&bodyTagIds, "tag-ids", "", "Tag ids")
	cmd.Flags().IntVar(&bodyTimeout, "timeout", 0, "Timeout")
	cmd.Flags().StringVar(&bodyType, "type", "", "Type")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
