// Copyright 2026 Jeremy and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMonitorsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "monitors",
		Short:       "List, get, create, update, and delete monitors",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newMonitorsCreateCmd(flags))
	cmd.AddCommand(newMonitorsDeleteCmd(flags))
	cmd.AddCommand(newMonitorsGetCmd(flags))
	cmd.AddCommand(newMonitorsListCmd(flags))
	cmd.AddCommand(newMonitorsListBatchCmd(flags))
	cmd.AddCommand(newMonitorsUpdateCmd(flags))
	cmd.AddCommand(newMonitorsUpdateIdCmd(flags))
	cmd.AddCommand(newMonitorsHeartbeatsCmd(flags))
	cmd.AddCommand(newMonitorsResetCmd(flags))
	cmd.AddCommand(newMonitorsStatsCmd(flags))
	cmd.AddCommand(newMonitorsTlsCmd(flags))
	return cmd
}
