// Copyright 2026 Jeremy and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newNotificationChannelsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "notification-channels",
		Short:       "List, get, create, update, and delete notification channels",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newNotificationChannelsCreateCmd(flags))
	cmd.AddCommand(newNotificationChannelsCreateNotificationchannelsCmd(flags))
	cmd.AddCommand(newNotificationChannelsDeleteCmd(flags))
	cmd.AddCommand(newNotificationChannelsGetCmd(flags))
	cmd.AddCommand(newNotificationChannelsListCmd(flags))
	cmd.AddCommand(newNotificationChannelsUpdateCmd(flags))
	cmd.AddCommand(newNotificationChannelsUpdateNotificationchannelsCmd(flags))
	return cmd
}
