// Copyright 2026 Jeremy and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPeekapingAuthCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "peekaping-auth",
		Short:       "Create and update peekaping auth",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPeekapingAuthCreateCmd(flags))
	cmd.AddCommand(newPeekapingAuthCreate2faCmd(flags))
	cmd.AddCommand(newPeekapingAuthCreate2fa2Cmd(flags))
	cmd.AddCommand(newPeekapingAuthCreate2fa3Cmd(flags))
	cmd.AddCommand(newPeekapingAuthCreateRefreshCmd(flags))
	cmd.AddCommand(newPeekapingAuthCreateRegisterCmd(flags))
	cmd.AddCommand(newPeekapingAuthUpdateCmd(flags))
	return cmd
}
