// Copyright 2026 Jeremy and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newStatusPagesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "status-pages",
		Short:       "List, get, create, update, and delete status pages",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newStatusPagesCreateCmd(flags))
	cmd.AddCommand(newStatusPagesDeleteCmd(flags))
	cmd.AddCommand(newStatusPagesGetCmd(flags))
	cmd.AddCommand(newStatusPagesGetStatuspagesCmd(flags))
	cmd.AddCommand(newStatusPagesGetStatuspages2Cmd(flags))
	cmd.AddCommand(newStatusPagesGetStatuspages3Cmd(flags))
	cmd.AddCommand(newStatusPagesGetStatuspages4Cmd(flags))
	cmd.AddCommand(newStatusPagesListCmd(flags))
	cmd.AddCommand(newStatusPagesUpdateCmd(flags))
	return cmd
}
