// Copyright 2026 Jeremy and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTagsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "tags",
		Short:       "List, get, create, update, and delete tags",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTagsCreateCmd(flags))
	cmd.AddCommand(newTagsDeleteCmd(flags))
	cmd.AddCommand(newTagsGetCmd(flags))
	cmd.AddCommand(newTagsListCmd(flags))
	cmd.AddCommand(newTagsUpdateCmd(flags))
	cmd.AddCommand(newTagsUpdateIdCmd(flags))
	return cmd
}
